# Generated by Django 3.0.4 on 2020-03-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customerinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=100)),
                ('Phonenumber', models.IntegerField(max_length=13, unique=True)),
                ('Client_Value', models.DecimalField(decimal_places=10, max_digits=19)),
                ('Email', models.EmailField(max_length=254)),
                ('protfolio_site', models.URLField(blank=True)),
            ],
        ),
    ]
